asset_manager/urls.py
from django.urls import path
from .views import *

app_name = 'asset_manager'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('connect/<pk>/', ConnectToAConnectionView.as_view(), name='connect'),
    path('<pk>/delete/', DeleteAConnection.as_view(), name='delete'),
]

project_db_asset_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('asset_manager.urls')),
    path('admin/', admin.site.urls),
]

asset_manager/models.py
from django.db import models


class Connection(models.Model):
    connection_name = models.CharField(max_length=50)
    db_host = models.CharField(max_length=255, verbose_name='Database Host')
    db_port = models.PositiveIntegerField(blank=True, verbose_name='Database Port')
    db_user = models.CharField(max_length=50, verbose_name='Database User')
    db_pass = models.CharField(max_length=255, verbose_name='Database Password')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

asset_manager/forms.py
from django import forms
from .models import Connection


class NewConnectionForm(forms.ModelForm):
    class Meta:
        model = Connection
        fields = '__all__'


class DatabaseExportImportForm(forms.Form):
    export_db_name = forms.CharField(
        max_length=50,
        label='Database Name to Export'
    )
    export_db_tables = forms.CharField(
        max_length=255,
        label='Table names to Export',
        required=False,
        help_text='Separate table names with comma (,)'
    )
    export_directory = forms.CharField(
        max_length=255,
        required=False,
        help_text='Move the exported database to another directory'
    )
    import_db_host = forms.CharField(
        max_length=255,
        label='Import Database Host',
        required=False,
        help_text='Host of the Database to import'
    )
    import_db_port = forms.IntegerField(
        label='Import Database Port',
        required=False,
        help_text='Port of the Database to import'
    )
    import_db_user = forms.CharField(
        max_length=50,
        label='Import Database User',
        required=False,
        help_text='User of the Database to Import'
    )
    import_db_pass = forms.CharField(
        max_length=255,
        widget=forms.PasswordInput,
        label='Import Database Password',
        required=False,
        help_text='Password of the User of the Database to Import'
    )
    download_sql = forms.BooleanField(
        label='Download SQL to PC',
        required=False,
        help_text='Unchecking this will leave the sql file in the server'
    )


class ColumnToDIrectoryCompareForm(forms.Form):
    db_name = forms.CharField(
        max_length=50,
        label='Database Name'
    )
    db_table = forms.CharField(
        max_length=50,
        label='Database Table Name to Connect'
    )
    db_column = forms.CharField(
        max_length=30,
        label='Database Column to Compare'
    )
    directory = forms.CharField(
        max_length=255,
        help_text='Directory to Check for matching files'
    )
    backup_directory = forms.CharField(
        max_length=255,
        help_text='Matched files will be backed up here'
    )
    restore_directory = forms.CharField(
        max_length=255,
        help_text='Backed up files will be restored here'
    )
    clear_restore_directory = forms.BooleanField(
        required=False,
        label='Clear restore directory before restoring files'
    )
    delete_backup_directory = forms.BooleanField(
        required=False,
        label='Delete backup directory when done'
    )

asset_manager/views.py
import os, shutil
from django.shortcuts import (
    render,
    redirect,
    reverse,
    get_object_or_404
)
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    FormView,
    DetailView,
    DeleteView
)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from mysql.connector import connect
from .models import Connection
from .forms import (
    NewConnectionForm,
    DatabaseExportImportForm,
    ColumnToDIrectoryCompareForm
)
from .asset_manager import AssetBackupRestore, DatabaseBackupRestore, AssetManager


class IndexView(SuccessMessageMixin, CreateView):
    template_name = 'asset_manager/index.html'
    form_class = NewConnectionForm
    success_url = reverse_lazy('asset_manager:index')
    success_message = "%(connection_name) was created successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['connections'] = Connection.objects.all()

        return context


class ConnectToAConnectionView(SuccessMessageMixin, DetailView):
    directory = None
    backup_directory = None
    restore_directory = None
    template_name = 'asset_manager/connect.html'
    model = Connection
    context_object_name = 'connection'

    def handle_form_invalid(self, request, **kwargs):
        return render(
            request,
            self.template_name,
            context={
                'connection': self.get_object(),
                **kwargs
            }
        )

    def handle_column_to_directory_compare(self, request, form):
        asset_backup_restore = AssetBackupRestore()
        asset_backup_restore.set_connection(self.get_object())
        asset_backup_restore.set_form(form)
        asset_manager = AssetManager()

        try:
            asset_manager.operate(asset_backup_restore)
        except Exception as e:
            messages.error(request, e)
            return redirect('asset_manager:connect', pk=self.kwargs['pk'])

        messages.success(request, 'Files are cleared')
        return redirect('asset_manager:connect', pk=self.kwargs['pk'])

    def handle_database_export_import(self, request, form):
        database_backup_restore = DatabaseBackupRestore()
        database_backup_restore.set_connection(self.get_object())
        database_backup_restore.set_form(form)
        asset_manager = AssetManager()

        try:
            asset_manager.operate(database_backup_restore)
        except Exception as e:
            if str(e) != '':
                messages.error(request, e)
                return redirect('asset_manager:connect', pk=self.kwargs['pk'])

        messages.success(request, 'Database imported')

        return redirect('asset_manager:connect', pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ColumnToDIrectoryCompareForm()
        context['form_database_export_import'] = DatabaseExportImportForm()

        return context

    def post(self, request, *args, **kwargs):
        if 'submit_asset_backup_restore' in request.POST:
            form = ColumnToDIrectoryCompareForm(request.POST)

            if not form.is_valid():
                return self.handle_form_invalid(
                    request,
                    form=form,
                    form_database_export_import=DatabaseExportImportForm()
                )

            return self.handle_column_to_directory_compare(request, form)
        elif 'submit_database_backup_restore' in request.POST:
            form = DatabaseExportImportForm(request.POST)

            if not form.is_valid():
                return self.handle_form_invalid(
                    request,
                    form=ColumnToDIrectoryCompareForm(),
                    form_database_export_import=form
                )

            return self.handle_database_export_import(
                request,
                form
            )


class DeleteAConnection(SuccessMessageMixin, DeleteView):
    model = Connection
    success_message = "%(connection_name) has been deleted"
    success_url = reverse_lazy('asset_manager:index')

asset_manager/templates/asset_manager/asset-backup-restore.html
<form method="post">
    {% csrf_token %}

    <div class="form-group row">
        <div class="col-md-12">
            <label for="{{ form.db_name.id_for_label }}">
                {{ form.db_name.label }}
            </label>
            <input type="text" name="{{ form.db_name.name }}" id="{{ form.db_name.id_for_label }}" class="form-control">

            {% if form.db_name.errors %}
                {% for error in form.db_name.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12">
            <label for="{{ form.db_table.id_for_label }}">
                {{ form.db_table.label }}
            </label>
            <input type="text" name="{{ form.db_table.name }}" id="{{ form.db_table.id_for_label }}" class="form-control">

            {% if form.db_table.errors %}
                {% for error in form.db_table.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12">
            <label for="{{ form.db_column.id_for_label }}">
                {{ form.db_column.label }}
            </label>
            <input type="text" name="{{ form.db_column.name }}" id="{{ form.db_column.id_for_label }}" class="form-control">

            {% if form.db_column.errors %}
                {% for error in form.db_column.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12">
            <label for="{{ form.directory.id_for_label }}">{{ form.directory.label }}</label>
            <input type="text" name="{{ form.directory.name }}" id="{{ form.directory.id_for_label }}" class="form-control" value="{{ form.directory.value|default_if_none:'' }}">
            <p><small class="tex-muted">{{ form.directory.help_text}} </small></p>

            {% if form.directory.errors %}
                {% for error in form.directory.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12">
            <label for="{{ form.backup_directory.id_for_label }}">{{ form.backup_directory.label }}</label>
            <input type="text" name="{{ form.backup_directory.name }}" id="{{ form.backup_directory.id_for_label }}" class="form-control" value="{{ form.backup_directory.value|default_if_none:'' }}">
            <p><small class="tex-muted">{{ form.backup_directory.help_text}} </small></p>

            {% if form.backup_directory.errors %}
                {% for error in form.backup_directory.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12">
            <label for="{{ form.restore_directory.id_for_label }}">{{ form.restore_directory.label }}</label>
            <input type="text" name="{{ form.restore_directory.name }}" id="{{ form.restore_directory.id_for_label }}" class="form-control" value="{{ form.restore_directory.value|default_if_none:'' }}">
            <p><small class="tex-muted">{{ form.restore_directory.help_text}} </small></p>

            {% if form.restore_directory.errors %}
                {% for error in form.restore_directory.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12">
            <input type="checkbox" name="{{ form.clear_restore_directory.name }}" id="{{ form.clear_restore_directory.id_for_label }}" value="true">
            <label for="{{ form.clear_restore_directory.id_for_label }}">{{ form.clear_restore_directory.label }}</label>
            <p><small class="tex-muted">{{ form.clear_restore_directory.help_text}} </small></p>

            {% if form.clear_restore_directory.errors %}
                {% for error in form.clear_restore_directory.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12">
            <input type="checkbox" name="{{ form.delete_backup_directory.name }}" id="{{ form.delete_backup_directory.id_for_label }}" value="true">
            <label for="{{ form.delete_backup_directory.id_for_label }}">{{ form.delete_backup_directory.label }}</label>
            <p><small class="tex-muted">{{ form.delete_backup_directory.help_text}} </small></p>

            {% if form.delete_backup_directory.errors %}
                {% for error in form.delete_backup_directory.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12">
            <input type="submit" name="submit_asset_backup_restore" value="Remove unmatched files" class="btn btn-danger float-right">
        </div>
    </div>
</form>

asset_manager/templates/asset_manager/connect.html
{% extends 'layouts/master.html' %}

{% block title %}{{ connection.connection_name }}{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-md-9 offset-1">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">
                        Connected To: {{ connection.connection_name }} ({{ connection.db_host }})
                    </li>
                </ol>
            </nav>

            {% if messages %}
                {% for message in messages %}
                    <p{% if message.tags %} class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}"{% endif %}>
                        {{ message }}
                    </p>
                {% endfor %}
            {% endif %}

            <div class="row">
                <div class="col-md-4">
                    <div class="nav flex-column nav-pills" id="manageTab" role="tablist" aria-orientation="vertical">
                        <a class="nav-link active" id="database-backup-restore-tab" data-toggle="pill" href="#database-backup-restore" role="tab" aria-controls="database-backup-restore" aria-selected="true">Database Backup/Restore</a>
                        <a class="nav-link" id="asset-backup-restore-tab" data-toggle="pill" href="#asset-backup-restore" role="tab" aria-controls="asset-backup-restore" aria-selected="true">Asset Backup/Restore</a>
                    </div>
                </div>

                <div class="col-md-8">
                    <div class="tab-content" id="manageTabContent">
                        <div class="tab-pane fade show active" id="database-backup-restore" role="tabpanel" aria-labelledby="database-backup-restore-tab">
                            {% include 'asset_manager/database-backup-restore.html' %}
                        </div>

                        <div class="tab-pane fade" id="asset-backup-restore" role="tabpanel" aria-labelledby="asset-backup-restore-tab">
                            {% include 'asset_manager/asset-backup-restore.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

asset_manager/templates/asset_manager/database-backup-restore.html
<form method="post">
    {% csrf_token %}

    {% for field in form_database_export_import.visible_fields %}
        <div class="form-group row">
            <div class="col-md-12">
                {% if field.name == 'download_sql' %}
                    <input type="checkbox" name="{{ field.name }}" id="{{ field.id_for_label }}" value="True">
                    <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    <p><small>{{ field.help_text }}</small></p>
                {% else %}
                    <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    <input type="text" name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-control">
                    {% if field.help_text %}
                        <p><small>{{ field.help_text }}</small></p>
                    {% endif %}
                {% endif %}
                

                {% if field.errors %}
                    {% for error in field.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    {% endfor %}

    <div class="form-group row">
        <div class="col-md-12">
            <input type="submit" name="submit_database_backup_restore" value="Start" class="btn btn-success float-right">
        </div>
    </div>
</form>

asset_manager/templates/asset_manager/index.html
{% extends 'layouts/master.html' %}

{% block title %}Home{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-md-6 offset-3">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                            {{ message }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}

            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#saved-connection" role="tab" aria-controls="saved-connection" aria-selected="true">Saved Connection</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="new-connection-tab" data-toggle="tab" href="#new-connection" role="tab" aria-controls="new-connection" aria-selected="false">New Connection</a>
                </li>
            </ul>

            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="saved-connection" role="tabpanel" aria-labelledby="saved-connection-tab">
                    <ul>
                        {% for connection in connections %}
                            <li>
                                <a href="{% url 'asset_manager:connect' pk=connection.id %}">{{ connection.connection_name }}</a> |
                                <a href="javascript:;" onclick="document.getElementById('connection-delete-form-{{ connection.id }}').submit()">Delete</a>
                            </li>

                            <form action="{% url 'asset_manager:delete' pk=connection.id %}" id="connection-delete-form-{{ connection.id }}" method="post" style="display: none;">
                                {% csrf_token %}
                            </form>
                        {% endfor %}
                    </ul>
                </div>

                <div class="tab-pane fade" id="new-connection" role="tabpanel" aria-labelledby="new-connection-tab">
                    <form method="post">
                        {% csrf_token %}

                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="{{ form.connection_name.id_for_label }}">
                                    {{ form.connection_name.label }}
                                </label>
                                <input type="text" name="{{ form.connection_name.name }}" id="{{ form.connection_name.id_for_label }}" class="form-control">

                                {% if form.connection_name.errors %}
                                    {% for error in form.connection_name.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="{{ form.db_host.id_for_label }}">
                                    {{ form.db_host.label }}
                                </label>
                                <input type="text" name="{{ form.db_host.name }}" id="{{ form.db_host.id_for_label }}" class="form-control">

                                {% if form.db_host.errors %}
                                    {% for error in form.db_host.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="{{ form.db_port.id_for_label }}">
                                    {{ form.db_port.label }}
                                </label>
                                <input type="number" name="{{ form.db_port.name }}" id="{{ form.db_port.id_for_label }}" class="form-control">

                                {% if form.db_port.errors %}
                                    {% for error in form.db_port.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="{{ form.db_user.id_for_label }}">
                                    {{ form.db_user.label }}
                                </label>
                                <input type="text" name="{{ form.db_user.name }}" id="{{ form.db_user.id_for_label }}" class="form-control">

                                {% if form.db_user.errors %}
                                    {% for error in form.db_user.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="{{ form.db_pass.id_for_label }}">
                                    {{ form.db_pass.label }}
                                </label>
                                <input type="password" name="{{ form.db_pass.name }}" id="{{ form.db_pass.id_for_label }}" class="form-control">

                                {% if form.db_pass.errors %}
                                    {% for error in form.db_pass.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                <input type="submit" value="Save" class="btn btn-primary float-right">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

templates/layouts/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} | DB Asset Manager</title>

    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'asset_manager:index' %}">DB Asset Manager</a>
    </nav>

    <br>
    
    <div class="container">
        {% block body %} {% endblock %}
    </div>

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>